name: Cargo build and test

on:
  push:
     branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: ${{matrix.toolchain}}
          override: true

      - name: Run Cargo test
        run: cargo test

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --ignore-tests

      - name: Install clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
      
      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit

